services:
  redis:
    image: "bitnami/redis:6.2.14"
    restart: unless-stopped
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis_data:/bitnami/redis/data

  postgres:
    image: pgvector/pgvector:0.6.2-pg16
    restart: unless-stopped
    environment:
      POSTGRES_DB: dembrane
      POSTGRES_USER: dembrane
      POSTGRES_PASSWORD: dembrane
    networks:
      - default
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.13
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=dembrane
      - RABBITMQ_DEFAULT_PASS=dembrane
    networks:
      - default
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  directus:
    restart: unless-stopped
    build:
      context: ./directus
      dockerfile: Dockerfile
    ports:
      - 8055:8055
    depends_on:
      - postgres
      - rabbitmq
    environment:
      SESSION_COOKIE_NAME: ${DIRECTUS_SESSION_COOKIE_NAME:-directus_session_token}
      PUBLIC_URL: ${DIRECTUS_PUBLIC_URL}
      PORT: 8055
      SECRET: ${DIRECTUS_SECRET}
      ADMIN_EMAIL: admin@dembrane.com
      ADMIN_PASSWORD: ${DIRECTUS_ADMIN_PASSWORD}
      ADMIN_TOKEN: ${DIRECTUS_ADMIN_TOKEN}
      WEBSOCKETS_ENABLED: true
      DB_CLIENT: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: dembrane
      DB_PASSWORD: dembrane
      DB_DATABASE: dembrane
      TELEMETRY: false
      REDIS_ENABLED: true
      REDIS: redis://redis:6379
      CORS_ENABLED: true
      CORS_ORIGIN: ${DIRECTUS_CORS_ORIGIN}
      CORS_CREDENTIALS: true
      SESSION_COOKIE_DOMAIN: ${DIRECTUS_SESSION_COOKIE_DOMAIN}
      SESSION_COOKIE_SAME_SITE: lax
      SESSION_COOKIE_SECURE: lax
      EMAIL_TRANSPORT: smtp
      EMAIL_FROM: ${SMTP_FROM:-DoNotReply@c1f65324-81a8-41de-abe3-2c1cbf52ba1a.azurecomm.net}
      EMAIL_SMTP_HOST: ${SMTP_HOST:-smtp.azurecomm.net}
      EMAIL_SMTP_PORT: ${SMTP_POST:-587}
      EMAIL_SMTP_USER: ${SMTP_USER:-Communication-Services-Pilot.062b802b-0df6-407b-8bd4-ecb66ec67c32.0e14b809-b0c5-474b-81ed-6c06d141123a}
      EMAIL_SMTP_PASSWORD: ${SMTP_PASSWORD}
      USER_REGISTER_URL_ALLOW_LIST: ${ADMIN_BASE_URL}/verify-email
      PASSWORD_RESET_URL_ALLOW_LIST: ${ADMIN_BASE_URL}/password-reset
      USER_INVITE_URL_ALLOW_LIST: ${ADMIN_BASE_URL}/invite
      AUTH_PROVIDERS: google
      AUTH_GOOGLE_DRIVER: openid
      AUTH_GOOGLE_CLIENT_ID: ${AUTH_GOOGLE_CLIENT_ID}
      AUTH_GOOGLE_CLIENT_SECRET: ${AUTH_GOOGLE_CLIENT_SECRET}
      AUTH_GOOGLE_ISSUER_URL: https://accounts.google.com
      AUTH_GOOGLE_IDENTIFIER_KEY: email
      AUTH_GOOGLE_FIRST_NAME_KEY: given_name
      AUTH_GOOGLE_LAST_NAME_KEY: family_name
      AUTH_GOOGLE_ICON: google
      AUTH_GOOGLE_LABEL: Google
      AUTH_GOOGLE_ALLOW_PUBLIC_REGISTRATION: true
      AUTH_GOOGLE_DEFAULT_ROLE_ID: 2446660a-ab6c-4801-ad69-5711030cba83
      AUTH_GOOGLE_REDIRECT_ALLOW_LIST: ${ADMIN_BASE_URL}/en-US/projects,${ADMIN_BASE_URL}/nl-NL/projects

    volumes:
      - ./directus/uploads:/directus/uploads

  api-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: unless-stopped
    command: /bin/sh /code/server/prod.sh
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 1m
      timeout: 10s
      retries: 3
    environment:
      - DIRECTUS_PUBLIC_URL=${DIRECTUS_PUBLIC_URL}
      - DIRECTUS_TOKEN=${DIRECTUS_ADMIN_TOKEN}
      - DIRECTUS_SECRET=${DIRECTUS_SECRET}
      - DIRECTUS_SESSION_COOKIE_NAME=${DIRECTUS_SESSION_COOKIE_NAME:-directus_session_token}
      - ADMIN_BASE_URL=${ADMIN_BASE_URL}
      - PARTICIPANT_BASE_URL=${PARTICIPANT_BASE_URL}
      - BUILD_VERSION=${BUILD_VERSION}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - RABBITMQ_URL=amqp://dembrane:dembrane@rabbitmq:5672
      - REDIS_URL=redis://redis:6379
      - DISABLE_REDACTION=1
      - DATABASE_URL=${DATABSE_URL:-postgresql+psycopg://dembrane:dembrane@postgres:5432/dembrane}
      - DISABLE_SENTRY=${DISABLE_SENTRY:-0}
      - SERVE_API_DOCS=${SERVE_API_DOCS:-0}
    env_file:
      - ./server/.env
    volumes:
      - ./server/uploads:/code/server/uploads
      - ./server/trankit_cache:/code/server/trankit_cache
    networks:
      - default
    depends_on:
      - directus

  worker:
    build:
      context: ./server
      dockerfile: Dockerfile
    command: /bin/sh /code/server/prod-worker.sh
    environment:
      - DIRECTUS_PUBLIC_URL=${DIRECTUS_PUBLIC_URL}
      - DIRECTUS_SECRET=${DIRECTUS_SECRET}
      - DIRECTUS_TOKEN=${DIRECTUS_ADMIN_TOKEN}
      - DIRECTUS_SESSION_COOKIE_NAME=${DIRECTUS_SESSION_COOKIE_NAME:-directus_session_token}
      - ADMIN_BASE_URL=${ADMIN_BASE_URL}
      - PARTICIPANT_BASE_URL=${PARTICIPANT_BASE_URL}
      - BUILD_VERSION=${BUILD_VERSION}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - RABBITMQ_URL=amqp://dembrane:dembrane@rabbitmq:5672
      - REDIS_URL=redis://redis:6379
      - DISABLE_REDACTION=1
      - DATABASE_URL=${DATABSE_URL:-postgresql+psycopg://dembrane:dembrane@postgres:5432/dembrane}
      - DISABLE_SENTRY=${DISABLE_SENTRY:-0}
      - SERVE_API_DOCS=${SERVE_API_DOCS:-0}
    env_file:
      - ./server/.env
    volumes:
      - ./server/uploads:/code/server/uploads
      - ./server/trankit_cache:/code/server/trankit_cache
    networks:
      - default
    depends_on:
      - api-server

  dashboard-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=${API_BASE_URL}/api
        - VITE_ADMIN_BASE_URL=${ADMIN_BASE_URL}
        - VITE_PARTICIPANT_BASE_URL=${PARTICIPANT_BASE_URL}
        - VITE_BUILD_VERSION=${BUILD_VERSION}
        - VITE_USE_PARTICIPANT_ROUTER=0
        - VITE_DIRECTUS_PUBLIC_URL=${DIRECTUS_PUBLIC_URL}
    restart: unless-stopped
    depends_on:
      - api-server

  participant-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=${API_BASE_URL}/api
        - VITE_PARTICIPANT_BASE_URL=${PARTICIPANT_BASE_URL}
        - VITE_BUILD_VERSION=${BUILD_VERSION}
        - VITE_USE_PARTICIPANT_ROUTER=1
        - VITE_DIRECTUS_PUBLIC_URL=${DIRECTUS_PUBLIC_URL}
    restart: unless-stopped
    networks:
      - default
    depends_on:
      - dashboard-frontend

volumes:
  postgres_data:
  rabbitmq_data:
  redis_data:

networks:
  default:
    driver: bridge
